---
- name: Add network interfaces to /etc/network/interfaces
  blockinfile:
    dest: /etc/network/interfaces
    block: |
        auto {{ item.int_name }}
          iface {{ item.int_name }} inet static
          address {{ item.ip_address }}
          netmask {{ item.netmask }}
          bridge_ports {{ item.bridge_ports }}
          bridge_stp {{ item.bridge_stp }}
          bridge_fd {{ item.bridge_fd }}
    insertafter: '^# ansible managed'
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.int_name }}"
  with_items:
      "{{ interfaces }}"
  notify: reload_networking
