---
- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: visudo -cf %s

- name: Add {{ sudoers }} sudoers to wheel group
  user:
    name: "{{ item }}"
    groups: wheel
    append: yes
    state: present 
    createhome: yes
  with_items: "{{ sudoers|default([]) }}"

- name: Add {{ users }} users to default group
  user:
    name: "{{ item }}"
    append: yes
    state: present 
    createhome: yes
  with_items: "{{ users|default([]) }}"

- name: Add SSH public keys
  authorized_key:
    user: "{{ item }}"
    state: present
    # authorized keys are only made of the followings, used to retract previous ones
    exclusive: yes
    key: "{{ lookup('pipe', 'cat ../pub_keys/{{ item }}/*.pub') }}"
  with_items: "{{ sudoers|default([])|list + users|default([])|list }}"
  when: personal_pubkey|default(true)
  