---
- name: Ensure fail2ban service is installed
  apt: 
    name: fail2ban
    state: present

- name: Enable service fail2ban
  systemd:
    name: fail2ban
    enabled: yes

- name: Copy jail.local
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: 755

- name: Copy proxmox.conf
  copy:
    src: proxmox.conf
    dest: /etc/fail2ban/filter.d/
  when: (proxmox_mode|default('none')) != 'none'

- name: Restart service fail2ban 
  systemd:
    name: fail2ban
    state: restarted
    daemon_reload: yes