- name: 'install python3-apt so native apt plugins work'
  package:
      name: 'python3-apt'
      state: 'present'
      
- name: 'install python3'
  apt:
    pkg:
      - python3
      - python3-dev
      - python3-pip
      - python3-setuptools
      - build-essential

- name: 'pip update pip'
  pip:
    executable: 'pip3'
    name: 'pip'
    state: 'latest'

- name: 'Install python dependencies'
  pip:
    executable: 'pip3'
    name: ['setuptools', 'virtualenv', 'proxmoxer']
    state: 'latest'