---
- name: 'Update all packages to the latest version'
  apt:
    upgrade: 'dist'

- name: 'install python3-apt so native apt plugins work'
  package:
      name: 'python3-apt'
      state: 'present'
      
- name: 'install python3'
  apt:
    pkg:
      - python3
      - python3-dev
      - python3-pip
      - python3-setuptools
      - build-essential

- name: 'pip update pip'
  pip:
    executable: 'pip3'
    name: 'pip'
    state: 'latest'

- name: 'Install python dependencies'
  pip:
    executable: 'pip3'
    name: ['setuptools', 'virtualenv', 'proxmoxer']
    state: 'latest'

- name: https certificate - prepare post hoot script
  template:
    src: letsencrypt-renew-certs.sh.j2
    dest: /usr/local/bin/renew-pve-certs.sh
    owner: root
    group: root
    mode: 0755

- name: https certificate - let's encrypt
  include_role:
    name: letsencrypt
  vars:
    certbot_post_hook: /usr/local/bin/renew-pve-certs.sh
  
- name: Restart service pveproxy 
  systemd:
    name: pveproxy
    state: restarted
    daemon_reload: yes
