---
- name: 'Update all packages to the latest version'
  apt:
    upgrade: 'dist'

- include_tasks: ansible.yml
- include_tasks: https.yml
- include_tasks: network.yml

- name: Restart service pveproxy 
  systemd:
    name: pveproxy
    state: restarted
    daemon_reload: yes
